// Объект с переводами для разных языков
const translations: Record<string, Record<string, string>> = {
  "en": {
    "loading": "Loading...",
    "personalizedFitnessJourney": "Your personalized fitness journey",
    "login": "Login",
    "register": "Register",
    "email": "Email",
    "password": "Password",
    "continue": "Continue",
    "dontHaveAccount": "Don't have an account?",
    "alreadyHaveAccount": "Already have an account?",
    "invalidCredentials": "Invalid email or password",
    "gender": "Gender",
    "genderHelp": "Choose your gender for personalized workout plan",
    "male": "Male",
    "female": "Female",
    "completeProfile": "Complete your profile",
    "completeProfileDesc": "Help us customize your fitness experience",
    "yourName": "Your name",
    "enterName": "Enter your name",
    "age": "Age",
    "years": "years",
    "weight": "Weight",
    "kg": "kg",
    "height": "Height",
    "cm": "cm",
    "complete": "Complete",
    "loggedOut": "Logged out successfully",
    "strength": "Strength",
    "cardio": "Cardio",
    "flexibility": "Flexibility",
    "profileSettings": "Profile Settings",
    "manageAccount": "Manage your account and settings",
    "personalInfo": "Personal Information",
    "name": "Name",
    "preferences": "Preferences",
    "notifications": "Notifications",
    "notificationsDesc": "Receive workout reminders and achievements",
    "darkMode": "Dark Mode",
    "darkModeDesc": "Use dark theme for the application",
    "language": "Language",
    "languageDesc": "Choose your preferred language",
    "english": "English",
    "russian": "Русский",
    "account": "Account",
    "logOut": "Log Out",
    "profileUpdated": "Profile updated successfully",
    "saveChanges": "Save Changes",
    "goodMorning": "Good Morning",
    "goodAfternoon": "Good Afternoon",
    "goodEvening": "Good Evening",
    "yourFitnessProfile": "Your fitness profile",
    "todaysGoal": "Today's Goal",
    "weeklyActivity": "Weekly Activity",
    "caloriesBurn": "Calories burned per day",
    "calories": "calories",
    "todaysTasks": "Today's Tasks",
    "completeExercises": "Complete exercises to improve your fitness",
    "taskCompleted": "Task Completed",
    "youCompleted": "You completed",
    "moreDetails": "More Details",
    "authRequired": "Authentication required",
    "pushUps": "Push-ups",
    "pushUpsDuration": "3 sets of 10 push-ups",
    "squats": "Squats",
    "squatsDuration": "3 sets of 15 squats",
    "lunges": "Lunges",
    "lungesDuration": "3 sets of 10 lunges per leg",
    "plank": "Plank",
    "plankDuration": "Hold for 30 seconds, 3 times",
    "dumbbellCurls": "Dumbbell Curls",
    "dumbbellCurlsDuration": "3 sets of 12 curls per arm",
    "running": "Running",
    "runningDuration": "Run for 20 minutes at moderate pace",
    "jumpingJacks": "Jumping Jacks",
    "jumpingJacksDuration": "3 sets of 30 jumping jacks",
    "jumpRope": "Jump Rope",
    "jumpRopeDuration": "Jump rope for 10 minutes",
    "burpees": "Burpees",
    "burpeesDuration": "3 sets of 10 burpees",
    "highKnees": "High Knees",
    "highKneesDuration": "High knees for 1 minute, 3 times",
    "hamstringStretch": "Hamstring Stretch",
    "hamstringStretchDuration": "Hold for 30 seconds on each leg",
    "shoulderStretch": "Shoulder Stretch",
    "shoulderStretchDuration": "Hold for 30 seconds on each side",
    "hipFlexorStretch": "Hip Flexor Stretch",
    "hipFlexorStretchDuration": "Hold for 30 seconds on each leg",
    "yogaPoses": "Yoga Poses",
    "yogaPosesDuration": "Hold each pose for 1 minute",
    "dynamicStretching": "Dynamic Stretching",
    "dynamicStretchingDuration": "5 minutes of dynamic stretching",
    "goBack": "Back",
    "bodyProblemsSurvey": "Body Issues Survey",
    "bodyProblemsSurveyDesc": "Select the areas of your body that you have issues with",
    "backPain": "Back",
    "neck": "Neck",
    "shoulders": "Shoulders",
    "arms": "Arms",
    "legs": "Legs",
    "knees": "Knees",
    "feet": "Feet",
    "chest": "Chest",
    "abdomen": "Abdomen",
    "noProblems": "No problems",
    "dietRestrictionsSurvey": "Dietary Restrictions",
    "dietRestrictionsSurveyDesc": "Select any dietary restrictions you have",
    "lactoseIntolerant": "Lactose Intolerant",
    "glutenFree": "Gluten-Free",
    "vegetarian": "Vegetarian",
    "vegan": "Vegan",
    "nutsAllergy": "Nuts Allergy",
    "seafoodAllergy": "Seafood Allergy",
    "citrusAllergy": "Citrus Allergy",
    "eggsAllergy": "Eggs Allergy",
    "soyAllergy": "Soy Allergy",
    "noDietRestrictions": "No Dietary Restrictions",
    "underweight": "Underweight",
    "normal": "Normal",
    "overweight": "Overweight",
    "obese": "Obese",
    "appName": "AR-FIT",
    "dashboard": "Dashboard",
    "workout": "Workout",
    "nutrition": "Nutrition",
    "profile": "Profile"
  },
  "ru": {
    "loading": "Загрузка...",
    "personalizedFitnessJourney": "Ваш персонализированный фитнес-путь",
    "login": "Вход",
    "register": "Регистрация",
    "email": "Электронная почта",
    "password": "Пароль",
    "continue": "Продолжить",
    "dontHaveAccount": "Нет аккаунта?",
    "alreadyHaveAccount": "Уже есть аккаунт?",
    "invalidCredentials": "Неверная почта или пароль",
    "gender": "Пол",
    "genderHelp": "Выберите ваш пол для персонализированного плана тренировок",
    "male": "Мужской",
    "female": "Женский",
    "completeProfile": "Заполните профиль",
    "completeProfileDesc": "Помогите нам настроить ваш фитнес-опыт",
    "yourName": "Ваше имя",
    "enterName": "Введите ваше имя",
    "age": "Возраст",
    "years": "лет",
    "weight": "Вес",
    "kg": "кг",
    "height": "Рост",
    "cm": "см",
    "complete": "Завершить",
    "loggedOut": "Вы успешно вышли из системы",
    "strength": "Сила",
    "cardio": "Кардио",
    "flexibility": "Гибкость",
    "profileSettings": "Настройки профиля",
    "manageAccount": "Управляйте своим аккаунтом и настройками",
    "personalInfo": "Личная информация",
    "name": "Имя",
    "preferences": "Предпочтения",
    "notifications": "Уведомления",
    "notificationsDesc": "Получайте напоминания о тренировках и достижениях",
    "darkMode": "Темный режим",
    "darkModeDesc": "Использовать темную тему для приложения",
    "language": "Язык",
    "languageDesc": "Выберите предпочитаемый язык",
    "english": "English",
    "russian": "Русский",
    "account": "Аккаунт",
    "logOut": "Выйти",
    "profileUpdated": "Профиль успешно обновлен",
    "saveChanges": "Сохранить изменения",
    "goodMorning": "Доброе утро",
    "goodAfternoon": "Добрый день",
    "goodEvening": "Добрый вечер",
    "yourFitnessProfile": "Ваш фитнес-профиль",
    "todaysGoal": "Цель на сегодня",
    "weeklyActivity": "Недельная активность",
    "caloriesBurn": "Сожжено калорий за день",
    "calories": "калорий",
    "todaysTasks": "Задания на сегодня",
    "completeExercises": "Выполните упражнения, чтобы улучшить свою физическую форму",
    "taskCompleted": "Задание выполнено",
    "youCompleted": "Вы выполнили",
    "moreDetails": "Подробнее",
    "authRequired": "Требуется авторизация",
    "pushUps": "Отжимания",
    "pushUpsDuration": "3 подхода по 10 отжиманий",
    "squats": "Приседания",
    "squatsDuration": "3 подхода по 15 приседаний",
    "lunges": "Выпады",
    "lungesDuration": "3 подхода по 10 выпадов на каждую ногу",
    "plank": "Планка",
    "plankDuration": "Удерживать 30 секунд, 3 раза",
    "dumbbellCurls": "Сгибания рук с гантелями",
    "dumbbellCurlsDuration": "3 подхода по 12 сгибаний на каждую руку",
    "running": "Бег",
    "runningDuration": "Бег в течение 20 минут в умеренном темпе",
    "jumpingJacks": "Прыжки «звездочка»",
    "jumpingJacksDuration": "3 подхода по 30 прыжков",
    "jumpRope": "Прыжки на скакалке",
    "jumpRopeDuration": "Прыжки на скакалке в течение 10 минут",
    "burpees": "Берпи",
    "burpeesDuration": "3 подхода по 10 берпи",
    "highKnees": "Высокие колени",
    "highKneesDuration": "Высокие колени в течение 1 минуты, 3 раза",
    "hamstringStretch": "Растяжка подколенных сухожилий",
    "hamstringStretchDuration": "Удерживать 30 секунд на каждую ногу",
    "shoulderStretch": "Растяжка плеч",
    "shoulderStretchDuration": "Удерживать 30 секунд на каждую сторону",
    "hipFlexorStretch": "Растяжка сгибателей бедра",
    "hipFlexorStretchDuration": "Удерживать 30 секунд на каждую ногу",
    "yogaPoses": "Позы йоги",
    "yogaPosesDuration": "Удерживать каждую позу в течение 1 минуты",
    "dynamicStretching": "Динамическая растяжка",
    "dynamicStretchingDuration": "5 минут динамической растяжки",
    "goBack": "Назад",
    "bodyProblemsSurvey": "Опрос о проблемных зонах",
    "bodyProblemsSurveyDesc": "Выберите области вашего тела, с которыми у вас есть проблемы",
    "backPain": "Спина",
    "neck": "Шея",
    "shoulders": "Плечи",
    "arms": "Руки",
    "legs": "Ноги",
    "knees": "Колени",
    "feet": "Стопы",
    "chest": "Грудь",
    "abdomen": "Живот",
    "noProblems": "Нет проблем",
    "dietRestrictionsSurvey": "Пищевые ограничения",
    "dietRestrictionsSurveyDesc": "Выберите пищевые ограничения, которые у вас есть",
    "lactoseIntolerant": "Непереносимость лактозы",
    "glutenFree": "Без глютена",
    "vegetarian": "Вегетарианство",
    "vegan": "Веганство",
    "nutsAllergy": "Аллергия на орехи",
    "seafoodAllergy": "Аллергия на морепродукты",
    "citrusAllergy": "Аллергия на цитрусовые",
    "eggsAllergy": "Аллергия на яйца",
    "soyAllergy": "Аллергия на сою",
    "noDietRestrictions": "Нет пищевых ограничений",
    "underweight": "Недовес",
    "normal": "Норма",
    "overweight": "Избыточный вес",
    "obese": "Ожирение",
    "appName": "AR-FIT",
    "dashboard": "Главная",
    "workout": "Тренировки",
    "nutrition": "Питание",
    "profile": "Профиль"
  }
};

// Получение текущего языка из localStorage
export const getLanguage = (): "en" | "ru" => {
  const storedLanguage = localStorage.getItem("ar-fit-language");
  return (storedLanguage as "en" | "ru") || "ru";
};

// Сохранение выбранного языка в localStorage
export const setLanguage = (language: "en" | "ru"): void => {
  localStorage.setItem("ar-fit-language", language);
};

// Функция перевода строк
export const t = (key: string, language: "en" | "ru" = "ru"): string => {
  if (!translations[language] || !translations[language][key]) {
    console.warn(`Translation missing for key: ${key}, language: ${language}`);
    return key;
  }
  return translations[language][key];
};
