// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guoqeownlpsnapnpucji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1b3Flb3dubHBzbmFwbnB1Y2ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTg0MDUsImV4cCI6MjA1OTI3NDQwNX0.hnMxi6HAO8iLPcvYB81Mmvd8LJCmW4BfZUhroiKWre4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);